---
- hosts: pace
  user: root
  vars: 
      node1: alpha
      node2: beta
      node1-ip: 192.168.0.221
      node2-ip: 192.168.0.222
  tasks: 
   - name: installing dbrd utils
     shell: apt-get install -y drbd8-utils
   - name: parted disk creation
     parted: 
       device: /dev/sdb
       number: 1
       state: present
   - name: zeroing the contents of the disk
     dd if=/dev/zero of=/dev/sdb1
   - name: copying drbd.conf file to /etc/
     template: 
       src: files/drbd.j2 
       dest: /etc/drbd.conf
   - name: loading the mod and creating the device
      command: "{{ item }}"
      with_items:
        - modprobe drbd
        - drbdadm create-md r0
   
- hosts: master
  user: root
  tasks:
   - name:
     command: "{{ item }}"
     with_items:
        - drbdadm up r0
        - drbdadm -- --overwrite-data-of-peer primary r0/0


- hosts: master
  user: root
  tasks:
   - name: only on one node 
     command: " {{ item }} "
     with_items: 
      - mkfs.ext4 /dev/drbd0
      - mkdir -p /var/www/html
      - mount /dev/drbd0 /var/www/html
      - echo "this is generated for the first time when it was mounted" > /var/www/html/index.html
    
- hosts: pace
  user: root
  tasks:
   - name: umounting and other
     command: " {{ item }}"
     with_items:
      - systemctl disable drbd
      - umount /var/www/htmlsudo drbdadm down r0
   - name: copy the corosync file to both servers
     template: 
          src: files/cocrosync.j2 
          dest: /etc/corosync/corosync.conf
   - name: restart the coro and pmaker
     command: " {{  item }} "
     with_items: 
      - systemctl restart corosync
      - systemctl start pacemaker 
      
